#======================
# General Settings
#======================

# Default parse type setting for non-explicit extension file.
# Allow value: "kukuri", "yarn", or "ink"
default_script_type = "kukuri"

# if true => separate each scene files
# if false => output into one bundle file
separate_output = true

# minify output setting
# if true => export minify json/gd file
minified_output = false

# Dialog text and command data output types.
# Allow value: "gd", "json"
outputs = ["gd", "json"]

# =====================
# Localization Settings
# =====================

# if false => discard localization settings
use_l10n_output = true

# Set original locale
# this value used for default dialog text locale
orig_locale = "ja_JP"

# Set Localization outputs
# Allow value: "po", "fluent", or "csv"
l10n_outputs = ["po"]

# =====================
# Output Settings
# =====================

output_dir = "./output"
l10n_output_dir = "./locale"
